### PR TITLE
 Experimental support for color counts..

### PR DESCRIPTION
**Pull request by ty7e**
Experimental support for color counts.
Added panel for color counts.
Button to see preview of the 1000 most common colors with visuals.
"Save" button will download an array with color counts for all colors in the image.

Preview is limited to most common colors because excessive DOM size causes lag.

### CODE REVIEW

**Comment by Catz-uwu** [comment]
more ideas:
only show alpha if alpha channel exists
way to toggle between hex and rgb(a)

**Comment by liwingyankobe** [comment]
Thank you guys!!!
More idea: You can look at how I implemented indexed color table and I think pretty much the same can be applied to here (even reusing the code). The interface can be more compact and we can make use of the original color picker with both RGBA and hex. Also, I don't think we need to show the top 1000 directly in any case, better to restrict it to ~100 and we can add a "More" button if we want, or just let users download the file if they need more than ~100.

**Comment by liwingyankobe** [comment]
Even better: why not just merge indexed color table and counter together into a single panel outside Advanced?

**Comment by Catz-uwu** [comment]
Yeah that sounds like a great idea! Here's what we're thinking in addition:

After pressing the general "color viewer" button, the panel contains a "counter" and a "colormap (gifs)" button. colormap option will be disabled for non-gifs.

Then we will add three new buttons:
1. compact / expanded toggle - toggles between the current color picker view, and the one tyte made. Expanded view shows the color count or gif color table index
2. sort (for non-gifs only) - you can sort by count
3. save - saves all color data into a file

Also an idea for the "more" button:
image
This container can scroll

**Comment by liwingyankobe** [comment]
Sorry for the long delay - I finally have time to finish the feature.

I added the two features Catz suggested (hex values and alpha channel adjustment). Also, I added page buttons so that people can view all the counts while keeping the interface clean. At the same time, I removed the save and clipboard features as they now don't fully fit in.

Regarding my previous comment, I decide to separate the UIs for color counts and indexed color table, as they represent different user needs. It may be beneficial if people can see all the color values and counts at the same time instead of one by one. The indexed color table may have duplicate or unused colors, which would look awkward in color counts. I will still put the color table under the same button in later commits though.

**Pull request merged**
